export const rhPaths = {
  dashboard: "/rh",
  legacy: "/rh/operacional",
  funcionarios: "/rh/funcionarios",
  novoFuncionario: "/rh/funcionarios/novo",
  funcionarioDetail: (id: string) => `/rh/funcionarios/${id}`,
  ponto: "/rh/ponto",
  pontoInconsistencias: "/rh/ponto/inconsistencias",
  pontoAjustes: "/rh/ponto/ajustes",
  ferias: "/rh/ferias",
  atestados: "/rh/atestados",
  folha: "/rh/folha",
  folhaCompetencia: (year: number, month: number) => `/rh/folha/${year}/${month}`,
  folhaFechamento: (year: number, month: number) => `/rh/folha/${year}/${month}/fechamento`,
  holerites: "/rh/holerites",
  holeriteDetail: (id: string) => `/rh/holerites/${id}`,
  configuracoes: "/rh/configuracoes",
  configuracoesBeneficios: "/rh/configuracoes/beneficios",
  configuracoesEncargos: "/rh/configuracoes/encargos",
  configuracoesRegras: "/rh/configuracoes/regras",
  configuracoesTabelasProgressivas: "/rh/configuracoes/tabelas-progressivas",
  auditoria: "/rh/auditoria",
  appAliases: {
    dashboard: "/app/rh",
    legacy: "/app/rh/operacional",
    funcionarios: "/app/rh/funcionarios",
    novoFuncionario: "/app/rh/funcionarios/novo",
    funcionarioDetail: (id: string) => `/app/rh/funcionarios/${id}`,
    ponto: "/app/rh/ponto",
    pontoInconsistencias: "/app/rh/ponto/inconsistencias",
    pontoAjustes: "/app/rh/ponto/ajustes",
    ferias: "/app/rh/ferias",
    atestados: "/app/rh/atestados",
    folha: "/app/rh/folha",
    folhaCompetencia: (year: number, month: number) => `/app/rh/folha/${year}/${month}`,
    folhaFechamento: (year: number, month: number) => `/app/rh/folha/${year}/${month}/fechamento`,
    holerites: "/app/rh/holerites",
    holeriteDetail: (id: string) => `/app/rh/holerites/${id}`,
    configuracoes: "/app/rh/configuracoes",
    configuracoesBeneficios: "/app/rh/configuracoes/beneficios",
    configuracoesEncargos: "/app/rh/configuracoes/encargos",
    configuracoesRegras: "/app/rh/configuracoes/regras",
    configuracoesTabelasProgressivas: "/app/rh/configuracoes/tabelas-progressivas",
    auditoria: "/app/rh/auditoria",
  },
} as const;
